### PR TITLE
fix: Redirect to previous page after logging in

### LINKED ISSUE #377: Redirect to previous page after logging in
Right now, after a successful log in users are redirected to the root page. However, a user may decide to log in (or sign up) clicking the "log in" button in the board page or in the comments section. After successful log in, those users should be redirected back to the page they were visiting.

### PR DESCRIPTION
**Pull request by askadityapandey**
This Pull Request fixes #377 issue.

### CODE REVIEW

**Comment by riggraz** [comment]
Hi @askadityapandey, thank you so much for your contribution!

I like your approach very much: simple and effective! However, I made some small fixes to make it work also for email sign in and not only oauth sign in. I also did a little bit of refactoring.

Can you give me write access to your fork repository so I can commit my changes?

Thanks again :)

**Comment by riggraz** [comment]
Okay I already had permissions to push to your fork 😅

I made some fixes and refactored a bit. In particular, the workflow should now also work for logins and registrations with email, and not just for oauths.

Let me know if you spot any possible problems or bugs!

**Comment by askadityapandey** [comment]
> Okay I already had permissions to push to your fork 😅
> 
> I made some fixes and refactored a bit. In particular, the workflow should now also work for logins and registrations with email, and not just for oauths.
> 
> Let me know if you spot any possible problems or bugs!

Hey, the changes look good to me! Lemme know if there's any else project you guys working on. Lately I was getting bored so thought let's contribute some, would love to do more on other projects too <3

**Comment by riggraz** [comment]
Actually I'm all in on Astuto, so I don't have any other projects to work on right now :(

If you want to further contribute to Astuto, I may suggest these issues:

- [Ask confirmation before discarding changes in site settings section](https://github.com/astuto/astuto/issues/106)
- [Add combobox for status change in post update form](https://github.com/astuto/astuto/issues/119)
- [Allow private comments](https://github.com/astuto/astuto/issues/418)
- [Make invitations expire after a certain amount of time](https://github.com/astuto/astuto/issues/425)

or take a look at the open issues, possibly the ones in milestone v2.0!

**Pull request merged**
