### PR TITLE
Add a slug field, used as a friendly id for boards

### LINKED ISSUE #40: Friendly URLs for boards
Right now a board has the following URL: `/boards/{board_id}`, where board_id is a number that denotes the ID of the board.

It would be nice to have friendly boards URL like: `/boards/{board_name}`, where board_name is the name of the board.

Maybe this last approach can cause problems, for example if a user bookmarks the URL of a board (e.g. `/boards/feature_requests`) but then the administrators change the name of the board (e.g. from "feature requests" to "features", hence URL becomes `/boards/features`), so the bookmarked link wouldn't work anymore. This problem won't happen by using the board id or by using another field for composing the url, such as a slug field.

Honestly I don't think this is such a big problem, but I'd appreciate feedback about it.

### PR DESCRIPTION
**Pull request by Vin0uz**
Refers and closes #40

:warning: For an existing app, it'd be necessary to adapt the migration,
because `null: false` constraint would be broken for slugs.

It might be just easier to use a gem such a [friendly+id](https://github.com/norman/friendly_id) : more features are available through it but are they needed ? I didn't know but completely open to discuss this topic :))

### CODE REVIEW

**Comment by Vin0uz** [comment]
Note for later : ensure to add seeds before merging this :)

**Comment by riggraz** [comment]
Hey Vin0uz 👋🏻

I thought about this problem for a while and that's what I came up with. We could either:

1. Create two migrations: one that just add a column for the slug but does not impose a NOT NULL constraint, and another that imposes the NOT NULL constraint. Then, as you said, we release a mini guide to explain that one with an already deployed instance must: i) run the first migration, ii) add values to slug field of all boards and iii) run the second migration.

2. Create a migration that also updates data, which is kind of unusual (and may be an antipattern?) but may work out in this case. The migration would look something like this:

```
# Add slug without NOT NULL constraint
add_column :boards, :slug, :string

# Update all boards providing a default slug (pseudo code here)
for each board, update board.slug = board.name.parametrize

# Enforce NOT NULL constraint
change_column_null :boards, :slug, true
```
This may be a bad practice because the database is not always created through migrations: it may well be initialized from the schema.rb file. But if this is the case, then this means the database has been created from scratch, so there is no problem about not null slugs.

Let me know if any of this makes sense to you 😁

**Comment by Vin0uz** [comment]
> Hey Vin0uz 👋🏻
> 
> I thought about this problem for a while and that's what I came up with. We could either:
> 
> 1. Create two migrations: one that just add a column for the slug but does not impose a NOT NULL constraint, and another that imposes the NOT NULL constraint. Then, as you said, we release a mini guide to explain that one with an already deployed instance must: i) run the first migration, ii) add values to slug field of all boards and iii) run the second migration.
> 2. Create a migration that also updates data, which is kind of unusual (and may be an antipattern?) but may work out in this case. The migration would look something like this:
> 
> ```
> # Add slug without NOT NULL constraint
> add_column :boards, :slug, :string
> 
> # Update all boards providing a default slug (pseudo code here)
> for each board, update board.slug = board.name.parametrize
> 
> # Enforce NOT NULL constraint
> change_column_null :boards, :slug, true
> ```
> 
> This may be a bad practice because the database is not always created through migrations: it may well be initialized from the schema.rb file. But if this is the case, then this means the database has been created from scratch, so there is no problem about not null slugs.
> 
> Let me know if any of this makes sense to you 😁

Sorry, took quite a time for me to get my hands back on this 🙈

I agree fully with your comment, the second approach is the one making the most sense to me (a unique migration to run, but antipattern, because if something fails on the way, that's nooo good 😬 )

I ll update my diff with appropriate content :)

**Comment by Vin0uz** [comment]
I squashed the commits, and added another commit about mimemagic (see commit message for more details). 

I don't think this commit belongs here, so if this pull request get too long, we should extract it and merge it asap, because I don't think we can deploy project as it is now 🤔

**Comment by riggraz** [comment]
Yeah I also found out about mimemagic problem. Actually I fixed it by running bundle update and the new Gemfile.lock has been commited on `main`.

I tried your code on a fresh installation and I get the following error:

```
I, [2021-04-29T19:20:15.503049 #67]  INFO -- : [188f4353-f50d-4e9b-91af-c59a284b7441] Started GET "/" for 172.18.0.1 at 2021-04-29 19:20:15 +0000
I, [2021-04-29T19:20:15.515763 #67]  INFO -- : [188f4353-f50d-4e9b-91af-c59a284b7441] Processing by StaticPagesController#roadmap as HTML
I, [2021-04-29T19:20:16.212353 #67]  INFO -- : [188f4353-f50d-4e9b-91af-c59a284b7441] Completed 500 Internal Server Error in 695ms (ActiveRecord: 206.9ms | Allocations: 3043)
F, [2021-04-29T19:20:16.216207 #67] FATAL -- : [188f4353-f50d-4e9b-91af-c59a284b7441]   
[188f4353-f50d-4e9b-91af-c59a284b7441] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "boards" does not exist
LINE 8:  WHERE a.attrelid = '"boards"'::regclass
                            ^
):
[188f4353-f50d-4e9b-91af-c59a284b7441]   
[188f4353-f50d-4e9b-91af-c59a284b7441] app/controllers/application_controller.rb:13:in `load_boards'
```

Do you encounter it as well?

**Pull request closed without merging**
