### PR TITLE
Feedback user!

### PR DESCRIPTION
**Pull request by Talha345**
User feedback!

### CODE REVIEW

**Comment by Talha345** [comment]
Merging branch!

**Comment by Vin0uz** [comment]
Hi Guys, and thanks a lot for contributing ! 

Is this meant to be a pull request ? If yes, could you please add content/context on why / what / why you are doing all this ? 

Nothing is yet noted in the [Contribution Guidelines](https://github.com/riggraz/astuto/wiki/Contribution-Guidelines) but I strongly encourage you to put (much) more details in your commit message : having 20 commits telling `Fix!` does not really help anyone to understand what you're trying to achieve 🙈

**Comment by Privatetm** [comment]
[Skip to content](https://github.com/orgs/community/discussions/86520#start-of-content)
[community](https://github.com/community)

[Overview](https://github.com/community)
[Repositories](https://github.com/orgs/community/repositories)
📦 Community-in-a-box #86520
 Locked
[ossanna16](https://github.com/ossanna16) started this conversation in [Discover](https://github.com/orgs/community/discussions/categories/discover)
[📦 Community-in-a-box](https://github.com/orgs/community/discussions/86520#top)
#86520
@ossanna16
2 weeks ago · 0 comments

[ossanna16](https://github.com/ossanna16)
[2 weeks ago](https://github.com/orgs/community/discussions/86520#discussion-6056963)
Community-in-a-BoX

🚀 Launch your own Discussions community immediately!
Created by GitHub community professionals, Community-in-a-box packages up tooling, resources, and knowledge, for organizations of all sizes to set up internal communities at scale.

💻 Who is it for?
Developers
Enterprise admins
Team leads & managers
Executive stakeholders
Product, project & program managers
Facilitators & coordinators
Students
💡Why Community-in-a box?
GitHub is a community of communities and a major proponent of InnerSource principles, and wants to provide all the resources you need to build and manage your own internal online communities using GitHub Discussions, a built-in free product that supports community building & management ([GitHub Community Discussions](https://github.com/orgs/community/discussions/) is where we use our own product to foster the GitHub Community) available within all GitHub organizations and repositories.

📦 What’s included in the “box”?
GitHub Discussions enablement: How-to use GitHub Discussions to foster InnerSource principles and build + manage internal communities of learning at scale
Resources: Access to a Discussions repository you can clone to get started with your community in no time
Knowledge base: Best practice resources, guides, community-related content
💡 How to use this document
The goal of this guide is to provide an overview of GitHub Discussions, and help you set up and manage your own internal GitHub Discussions community.

❓What is GitHub Discussions?
🤔 Why use GitHub Discussions?
📁 Enabling GitHub Discussions on your repository

Repository owners and people with write access can [enable GitHub Discussions on their public and private repositories](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) (⬅️ the link will guide you to the GitHub Docs and help you enable Discussions on your repo). The visibility of a discussion is inherited from the repository the discussion is created in.

💻 Enabling GitHub Discussions on your organization
⁉️ Repository- vs. organization level Discussions
🏆 Overview: Managing a successful internal Discussions community
💬 Deep dive: Discussions moderation
🛣️ Going the extra mile: Engagement & content creation
📚 Further reading
✅ Community checklist
Replies:0 comments
An owner of this repository has limited the ability to comment from new users.
Category
📚
Discover
Labels
Enterprise
Best Practices
Show & Tell
Enterprise Admin
1 participant
@ossanna16
Notifications
You’re not receiving notifications from this thread.
Events
ossanna16 Locked 2w
Footer
© 2024 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact
Manage cookies
Do not share my personal information
📦 Community-in-a-box · community · Discus. #114488 +2347084671254

**Comment by Privatetm** [comment]
Privatetmm882@gmail.com [Skip to content](https://github.com/orgs/community/discussions/114488#start-of-content)
[community](https://github.com/community)

[Overview](https://github.com/community)
[Repositories](https://github.com/orgs/community/repositories)
📦 Community-in-a-box #115436
 Locked
[ossanna16](https://github.com/ossanna16) started this conversation in [Discover](https://github.com/orgs/community/discussions/categories/discover)
[📦 Community-in-a-box](https://github.com/orgs/community/discussittmm#114488 )
@privatetmm 11

7weeks ago · 0 comments

[ossanna16](https://github.com/ossanna16)
[7weeks ago](https://github.com/orgs/community/discussions/13478#discussion-1144889)
Community-in-a-BoX

💰💰Launch your own Discussions community immediately!
Created by GitHub community professionals, Community-in-a-box packages up tooling, resources, and knowledge, for organizations of all sizes to set up internal communities at scale.

💻 Who is it for?
Developers
Enterprise admins
Team leads & managers
Executive stakeholders
Product, project & program managers
Facilitators & coordinators
Students
💡Why Community-in-a box?
GitHub is a community of communities and a major proponent of InnerSource principles, and wants to provide all the resources you need to build and manage your own internal online communities using GitHub Discussions, a built-in free product that supports community building & management ([GitHub Community Discussions](https://github.com/orgs/community/discussions/) is where we use our own product to foster the GitHub Community) available within all GitHub organizations and repositories.

📦 What’s included in the “box”?
GitHub Discussions enablement: How-to use GitHub Discussions to foster InnerSource principles and build + manage internal communities of learning at scale
Resources: Access to a Discussions repository you can clone to get started with your community in no time
Knowledge base: Best practice resources, guides, community-related content
💡 How to use this document
The goal of this guide is to provide an overview of GitHub Discussions, and help you set up and manage your own internal GitHub Discussions community.

What is GitHub Discussions?
📈💰 Why use GitHub Discussions?
📁 Enabling GitHub Discussions on your repository

Repository owners and people with write access can [enable GitHub Discussions on their public and private repositories](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) (⬅️ the link will guide you to the GitHub Docs and help you enable Discussions on your repo). The visibility of a discussion is inherited from the repository the discussion is created in.

💻 Enabling GitHub Discussions on your organization
⁉️ Repository- vs. organization level Discussions
🏆 Overview: Managing a successful internal Discussions community
💬 Deep dive: Discussions moderation
🛣️ Going the extra mile: Engagement & content creation
📚 Further reading
✅ Community checklist
Replies:0 comments
An owner of this repository has limited the ability to comment from new users.
Category
📚
Discover
Labels
Enterprise
Best Practices
Show & Tell
Enterprise Admin
1 participant
@ossanna16
Notifications
You’re not receiving notifications from this thread.
Events
ossanna16 Locked 2w
Footer
© 2024 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact
Manage cookies
Do not share my personal information
📦 Community-in-a-box · community · Discussion #33987

**Pull request closed without merging**
