### PR TITLE
Extract common env vars for enhanced readability

### PR DESCRIPTION
**Pull request by rishabhj1717**
- Use fragments and extensions to extract common env vars
  thereby improving readability of the docker-compose file
  used for dev-setup.
- Fixes issue #167.

### CODE REVIEW

**Comment by rishabhj1717** [comment]
@riggraz Can you please review this pull request 🙏 I have tested this locally and am able to load the site successfully 😄

**Comment by riggraz** [comment]
Hi @rishabhj1717 thanks so much for the PR!

I made some edits to remove the comments and be more concise:

```
services:
  db:
    image: postgres:14.5
    environment: &db-env
      POSTGRES_USER: astuto
      POSTGRES_PASSWORD: dbpass
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      <<: *db-env
      BASE_URL: http://localhost:3000
      SECRET_KEY_BASE: secretkeybasehere
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata:
```

I find this a little bit more understandable, because db env variables are kept under the `db` service and not on top.

What do you think? If it makes sense to you, can you give me write access to your astuto's fork or can you change the `docker-compose.yml` as suggested above?

Thanks again :)

**Comment by rishabhj1717** [comment]
The suggestion makes sense. Shall update the PR. Thank you @riggraz

**Comment by rishabhj1717** [comment]
@riggraz The changes have been made and the PR is updated. Kindly re-review it once 🙏

**Comment by riggraz** [comment]
Looks good, merging now ;)

**Pull request merged**
